name: effect
description: Dart port of the JavaScript effect framework
version: 1.0.0
# repository: https://github.com/my_org/my_repo
environment:
  sdk: ^3.3.0

dev_dependencies:
  test: ^1.24.0
  very_good_analysis: ^5.1.0
