name: effect
description: Dart port of the JavaScript effect framework
version: 0.0.1
repository: https://github.com/Goddchen/effect
environment:
  sdk: ^3.3.0

dev_dependencies:
  test: ^1.24.0
  very_good_analysis: ^5.1.0
dependencies:
  equatable: ^2.0.5
