on:
  push:
    branches:
      - "main"

jobs:
  causality_dart_package:
    runs-on: ubuntu-22.04
    steps:
      - uses: ./.github/actions/dart_package
        with:
          working_directory: packages/causality/
  flutter_causality_dart_package:
    runs-on: ubuntu-22.04
    steps:
      - uses: ./.github/actions/dart_package
        with:
          working_directory: packages/flutter_causality/
