on:
  pull_request:

jobs:
  causality_dart_package:
    runs-on: ubuntu-22.04
    steps:
      - uses: ./.github/actions/dart_package
        with:
          working_directory: packages/causality/
  flutter_causality_dart_package:
    runs-on: ubuntu-22.04
    steps:
      - uses: ./.github/actions/dart_package
        with:
          working_directory: packages/flutter_causality/
  semantic_pull_request:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/semantic_pull_request.yml@v1
